name: CI

on:
  workflow_dispatch:

jobs:
  build-blog:
    runs-on: ubuntu-latest

    steps:
      - uses: ThomasFerro/golb@v0.0.3

      - name: Test dist
        run: |
          ls,
          ls dist
